POST http://localhost:8000/apiDRF/book/

[{
    "title": "Les Chroniques de Narnia",
    "author": "Rodrigues Zager",
    "year": "09-11-6440",
    "pages": "60",
    "price": "509.53"
},
{
    "title": "Frankenstein",
    "author": "Lianna Smelser",
    "year": "04-10-7012",
    "pages": "2",
    "price": "616.13"
},
{
    "title": "Les Cerfs-volants de Kaboul",
    "author": "Rosella Woodworth",
    "year": "20-08-0519",
    "pages": "31",
    "price": "860.71"
},
{
    "title": "L'Alchimiste",
    "author": "Daniel Lumsden",
    "year": "01-12-0546",
    "pages": "5",
    "price": "319.21"
},
{
    "title": "Autant en emporte le vent",
    "author": "Broderick Frye",
    "year": "31-10-9406",
    "pages": "374",
    "price": "332.83"
},
{
    "title": "Les Trois Mousquetaires",
    "author": "Stephanee Grainger",
    "year": "01-03-6811",
    "pages": "3",
    "price": "327.90"
},
{
    "title": "Les Chroniques de Narnia",
    "author": "Ailene Wier",
    "year": "03-01-0396",
    "pages": "482",
    "price": "204.55"
},
{
    "title": "Moby-Dick",
    "author": "Paul Pawlak",
    "year": "02-07-7646",
    "pages": "221",
    "price": "316.80"
},
{
    "title": "Jane Eyre",
    "author": "Myranda Bonetti",
    "year": "31-11-4458",
    "pages": "195",
    "price": "304.51"
},
{
    "title": "Da Vinci Code",
    "author": "Amol Cardinal",
    "year": "04-08-4576",
    "pages": "55",
    "price": "612.22"
},
{
    "title": "La Couleur Pourpre",
    "author": "Sharli Goggin",
    "year": "01-03-5402",
    "pages": "86",
    "price": "391.13"
},
{
    "title": "Les Chroniques de Narnia",
    "author": "Veonica Rosier",
    "year": "07-10-1271",
    "pages": "10",
    "price": "198.29"
},
{
    "title": "Hunger Games",
    "author": "Delania Pitcher",
    "year": "04-03-9206",
    "pages": "5",
    "price": "512.75"
},
{
    "title": "L'Odyssée",
    "author": "Rheanna Monzon",
    "year": "22-05-0188",
    "pages": "5",
    "price": "101.78"
},
{
    "title": "L'Odyssée",
    "author": "Erlin Blazer",
    "year": "30-12-0910",
    "pages": "2",
    "price": "051.36"
},
{
    "title": "Autant en emporte le vent",
    "author": "Destinie Yocum",
    "year": "15-11-3428",
    "pages": "20",
    "price": "677.26"
},
{
    "title": "Le Hobbit",
    "author": "Kennita Vidal",
    "year": "31-06-4513",
    "pages": "84",
    "price": "411.81"
},
{
    "title": "Les Chroniques de Narnia",
    "author": "Shereka Mundell",
    "year": "27-12-8922",
    "pages": "553",
    "price": "002.52"
},
{
    "title": "Hunger Games",
    "author": "Tiffony Yerkes",
    "year": "29-07-5836",
    "pages": "08",
    "price": "751.78"
},
{
    "title": "Gatsby le Magnifique",
    "author": "Laterrica Armas",
    "year": "30-11-1813",
    "pages": "7",
    "price": "262.26"
},
{
    "title": "Hunger Games",
    "author": "Femi Leftwich",
    "year": "19-10-4674",
    "pages": "038",
    "price": "067.27"
},
{
    "title": "Moby-Dick",
    "author": "Granville Bernardi",
    "year": "18-02-5729",
    "pages": "82",
    "price": "625.43"
},
{
    "title": "Les Trois Mousquetaires",
    "author": "Allie Tewksbury",
    "year": "02-12-6192",
    "pages": "468",
    "price": "830.27"
},
{
    "title": "Autant en emporte le vent",
    "author": "Alston Holzer",
    "year": "02-12-6099",
    "pages": "87",
    "price": "315.13"
},
{
    "title": "Moby-Dick",
    "author": "Joeanthony Krull",
    "year": "04-01-5421",
    "pages": "158",
    "price": "523.98"
},
{
    "title": "L'Attrape-cœurs",
    "author": "Leandra Martine",
    "year": "03-01-4640",
    "pages": "5",
    "price": "534.14"
},
{
    "title": "Moby-Dick",
    "author": "Vick Carlino",
    "year": "26-12-5903",
    "pages": "08",
    "price": "397.01"
},
{
    "title": "Abattoir 5",
    "author": "Kashawn Martindale",
    "year": "11-09-8064",
    "pages": "335",
    "price": "838.03"
},
{
    "title": "Nos étoiles contraires",
    "author": "Estera Hall",
    "year": "28-12-9086",
    "pages": "0",
    "price": "191.22"
},
{
    "title": "L'Odyssée",
    "author": "Diedra Mares",
    "year": "06-11-9300",
    "pages": "119",
    "price": "707.41"
},
{
    "title": "1984",
    "author": "Meyosha Durr",
    "year": "03-12-3374",
    "pages": "0",
    "price": "639.56"
},
{
    "title": "Le Seigneur des Anneaux",
    "author": "Dyshaun Pfaff",
    "year": "30-08-3830",
    "pages": "1",
    "price": "664.85"
},
{
    "title": "Da Vinci Code",
    "author": "Sindy Jakes",
    "year": "06-10-3784",
    "pages": "43",
    "price": "617.37"
},
{
    "title": "Autant en emporte le vent",
    "author": "Dominic Ye",
    "year": "30-08-7902",
    "pages": "431",
    "price": "243.72"
},
{
    "title": "Harry Potter à l'école des sorciers",
    "author": "Gavin Dick",
    "year": "31-05-4502",
    "pages": "7",
    "price": "817.35"
},
{
    "title": "Nos étoiles contraires",
    "author": "Zackary Gustin",
    "year": "23-02-5046",
    "pages": "4",
    "price": "741.40"
},
{
    "title": "Le Hobbit",
    "author": "Malina Lachapelle",
    "year": "09-04-6531",
    "pages": "413",
    "price": "165.80"
},
{
    "title": "Le Hobbit",
    "author": "Jamesmichael Chaput",
    "year": "23-12-5517",
    "pages": "79",
    "price": "897.73"
},
{
    "title": "Le Meilleur des Mondes",
    "author": "Tin Konrad",
    "year": "09-08-4087",
    "pages": "76",
    "price": "143.98"
},
{
    "title": "Le Seigneur des Anneaux",
    "author": "Mitcheal Webb",
    "year": "01-07-6804",
    "pages": "6",
    "price": "828.15"
},
{
    "title": "La Couleur Pourpre",
    "author": "Endya Gravelle",
    "year": "04-06-7031",
    "pages": "1",
    "price": "104.37"
},
{
    "title": "Deuxième Partie de Vie de Charles Dickens",
    "author": "Tenell Hoppe",
    "year": "15-05-7568",
    "pages": "6",
    "price": "507.20"
},
{
    "title": "Frankenstein",
    "author": "Jordache Geiger",
    "year": "10-08-7902",
    "pages": "55",
    "price": "383.02"
},
{
    "title": "Da Vinci Code",
    "author": "Imran Devito",
    "year": "31-01-0998",
    "pages": "5",
    "price": "658.29"
},
{
    "title": "L'Alchimiste",
    "author": "Chisholm Collum",
    "year": "06-09-5400",
    "pages": "34",
    "price": "887.09"
},
{
    "title": "Hunger Games",
    "author": "Hadley Dison",
    "year": "01-12-2180",
    "pages": "246",
    "price": "815.98"
},
{
    "title": "Gatsby le Magnifique",
    "author": "Salote Reider",
    "year": "21-09-9127",
    "pages": "673",
    "price": "156.93"
},
{
    "title": "Gatsby le Magnifique",
    "author": "Mario Dennison",
    "year": "01-01-4316",
    "pages": "59",
    "price": "368.21"
},
{
    "title": "Millénium, Tome 1 : Les Hommes qui n'aimaient pas les femmes",
    "author": "Merl Coldwell",
    "year": "06-11-0620",
    "pages": "2",
    "price": "632.35"
},
{
    "title": "Millénium, Tome 1 : Les Hommes qui n'aimaient pas les femmes",
    "author": "Tandria Dunham",
    "year": "30-07-2395",
    "pages": "46",
    "price": "286.08"
},
{
    "title": "Abattoir 5",
    "author": "Celise Laguna",
    "year": "18-05-3221",
    "pages": "22",
    "price": "637.23"
},
{
    "title": "Deuxième Partie de Vie de Charles Dickens",
    "author": "Regina Filson",
    "year": "18-12-8185",
    "pages": "675",
    "price": "198.98"
},
{
    "title": "Deuxième Partie de Vie de Charles Dickens",
    "author": "Aureliano Pipkins",
    "year": "16-12-1941",
    "pages": "2",
    "price": "767.65"
},
{
    "title": "Ne tirez pas sur l'oiseau moqueur",
    "author": "Lesley Cullins",
    "year": "26-02-3575",
    "pages": "7",
    "price": "136.29"
},
{
    "title": "Les Chroniques de Narnia",
    "author": "Lorenia Mulcahy",
    "year": "24-12-9399",
    "pages": "19",
    "price": "137.50"
},
{
    "title": "Hunger Games",
    "author": "Reeshemah Prescott",
    "year": "29-06-1704",
    "pages": "73",
    "price": "973.44"
},
{
    "title": "L'Alchimiste",
    "author": "Turell Wiese",
    "year": "08-12-7829",
    "pages": "5",
    "price": "179.17"
},
{
    "title": "1984",
    "author": "Rachell Grinder",
    "year": "29-06-9479",
    "pages": "4",
    "price": "260.18"
},
{
    "title": "Da Vinci Code",
    "author": "Torri Cashman",
    "year": "21-04-0128",
    "pages": "3",
    "price": "458.78"
},
{
    "title": "Les Chroniques de Narnia",
    "author": "Kortni Perez",
    "year": "02-11-7159",
    "pages": "09",
    "price": "732.29"
},
{
    "title": "Millénium, Tome 1 : Les Hommes qui n'aimaient pas les femmes",
    "author": "Adriann Bayliss",
    "year": "30-11-5574",
    "pages": "7",
    "price": "713.54"
},
{
    "title": "L'Alchimiste",
    "author": "Shenna Escoto",
    "year": "31-11-2207",
    "pages": "3",
    "price": "269.84"
},
{
    "title": "Autant en emporte le vent",
    "author": "Wilisha Rex",
    "year": "08-09-1687",
    "pages": "56",
    "price": "274.02"
},
{
    "title": "1984",
    "author": "Jilian Gines",
    "year": "31-02-7543",
    "pages": "986",
    "price": "633.13"
},
{
    "title": "Le Meilleur des Mondes",
    "author": "Yecenia Hagans",
    "year": "06-01-2504",
    "pages": "55",
    "price": "078.04"
},
{
    "title": "1984",
    "author": "Moishe Tingle",
    "year": "09-10-7562",
    "pages": "5",
    "price": "034.11"
},
{
    "title": "Harry Potter à l'école des sorciers",
    "author": "Jamese Hovis",
    "year": "31-12-2130",
    "pages": "33",
    "price": "442.18"
},
{
    "title": "Abattoir 5",
    "author": "Mansi Pardee",
    "year": "01-03-5595",
    "pages": "9",
    "price": "572.03"
},
{
    "title": "Deuxième Partie de Vie de Charles Dickens",
    "author": "Collene Spoon",
    "year": "18-10-2760",
    "pages": "7",
    "price": "405.26"
},
{
    "title": "Deuxième Partie de Vie de Charles Dickens",
    "author": "Iona Nicolas",
    "year": "01-07-0255",
    "pages": "53",
    "price": "554.00"
},
{
    "title": "Le Seigneur des Anneaux",
    "author": "Georg Casto",
    "year": "09-11-9847",
    "pages": "520",
    "price": "108.50"
},
{
    "title": "Gatsby le Magnifique",
    "author": "Niccole Murchison",
    "year": "28-10-5901",
    "pages": "75",
    "price": "919.49"
},
{
    "title": "Deuxième Partie de Vie de Charles Dickens",
    "author": "Maichael Loveland",
    "year": "30-11-2051",
    "pages": "77",
    "price": "666.94"
},
{
    "title": "Orgueil et Préjugés",
    "author": "Nicholes Higgs",
    "year": "01-10-5052",
    "pages": "79",
    "price": "610.41"
},
{
    "title": "Ne tirez pas sur l'oiseau moqueur",
    "author": "Azure Sykes",
    "year": "01-06-6504",
    "pages": "61",
    "price": "759.91"
},
{
    "title": "Les Trois Mousquetaires",
    "author": "Alesandra Martina",
    "year": "31-06-5107",
    "pages": "3",
    "price": "386.13"
},
{
    "title": "1984",
    "author": "Vickey Digiacomo",
    "year": "23-11-8458",
    "pages": "0",
    "price": "526.90"
},
{
    "title": "Le Trône de Fer",
    "author": "Aldrich Childs",
    "year": "07-05-0103",
    "pages": "084",
    "price": "418.59"
},
{
    "title": "Cent Ans de Solitude",
    "author": "Deeandra Friedrich",
    "year": "06-10-8800",
    "pages": "8",
    "price": "662.27"
},
{
    "title": "Le Seigneur des Anneaux",
    "author": "Zoltan Swiderski",
    "year": "30-11-6729",
    "pages": "0",
    "price": "020.30"
},
{
    "title": "Harry Potter à l'école des sorciers",
    "author": "Sharise Malmberg",
    "year": "31-03-0723",
    "pages": "397",
    "price": "115.90"
},
{
    "title": "Le Meilleur des Mondes",
    "author": "Jahvon Kirkendall",
    "year": "03-12-0058",
    "pages": "13",
    "price": "381.41"
},
{
    "title": "Frankenstein",
    "author": "Kerek Peloquin",
    "year": "30-12-3343",
    "pages": "889",
    "price": "138.85"
},
{
    "title": "Les Cerfs-volants de Kaboul",
    "author": "Willow Peckham",
    "year": "10-03-6911",
    "pages": "51",
    "price": "994.34"
},
{
    "title": "Les Cerfs-volants de Kaboul",
    "author": "Benjmain Charlton",
    "year": "06-05-9239",
    "pages": "85",
    "price": "227.86"
},
{
    "title": "Ne tirez pas sur l'oiseau moqueur",
    "author": "Georgianna Hammers",
    "year": "03-10-6454",
    "pages": "32",
    "price": "764.20"
},
{
    "title": "L'Alchimiste",
    "author": "Marlayna Moreira",
    "year": "19-04-6767",
    "pages": "3",
    "price": "251.04"
},
{
    "title": "Le Meilleur des Mondes",
    "author": "Terrion Moll",
    "year": "30-02-9526",
    "pages": "383",
    "price": "047.59"
},
{
    "title": "Cent Ans de Solitude",
    "author": "Elle Hathorn",
    "year": "31-02-9071",
    "pages": "180",
    "price": "393.08"
},
{
    "title": "Le Meilleur des Mondes",
    "author": "Kayliegh Aldaco",
    "year": "31-06-6695",
    "pages": "76",
    "price": "555.55"
},
{
    "title": "Le Hobbit",
    "author": "Raeann Dinh",
    "year": "30-10-5704",
    "pages": "71",
    "price": "292.51"
},
{
    "title": "Moby-Dick",
    "author": "Priscillia Yerkes",
    "year": "30-11-7880",
    "pages": "4",
    "price": "027.47"
},
{
    "title": "Le Trône de Fer",
    "author": "Crystalina Stover",
    "year": "03-03-3488",
    "pages": "16",
    "price": "684.63"
},
{
    "title": "Ne tirez pas sur l'oiseau moqueur",
    "author": "Meira Pang",
    "year": "30-12-0279",
    "pages": "3",
    "price": "931.32"
},
{
    "title": "L'Alchimiste",
    "author": "Searra Bittle",
    "year": "08-11-8750",
    "pages": "459",
    "price": "884.35"
},
{
    "title": "Frankenstein",
    "author": "Lelani Neilson",
    "year": "30-12-3790",
    "pages": "7",
    "price": "811.56"
},
{
    "title": "Abattoir 5",
    "author": "Chantz Witte",
    "year": "30-11-9251",
    "pages": "7",
    "price": "052.92"
},
{
    "title": "L'Attrape-cœurs",
    "author": "Jackqueline Mercedes",
    "year": "06-10-9560",
    "pages": "167",
    "price": "730.47"
},
{
    "title": "Moby-Dick",
    "author": "Cornisha Pichardo",
    "year": "02-11-5273",
    "pages": "651",
    "price": "359.94"
},
{
    "title": "Gatsby le Magnifique",
    "author": "Meg Urich",
    "year": "02-09-8663",
    "pages": "791",
    "price": "588.44"
}]