# Generated by Django 5.0.2 on 2024-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Toto', max_length=100),
        ),
    ]
