# Generated by Django 5.0.2 on 2024-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text="L'auteur du livre", max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(help_text='Le nombre de pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Le prix du livre', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Toto', help_text='Le titre du livre', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(help_text="L'année de parution"),
        ),
    ]
