# Generated by Django 5.0.2 on 2024-02-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_book_author_alter_book_pages_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Le titre du livre', max_length=100),
        ),
    ]
