# Generated by Django 5.0.2 on 2024-02-20 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_book_author_alter_book_pages_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Le prix du livre', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.3)]),
        ),
    ]
