# Generated by Django 5.0.2 on 2024-02-21 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', help_text='Le prix du livre', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.3)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', help_text='Le titre du livre', max_length=100),
        ),
    ]
