# Generated by Django 5.0.2 on 2024-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_alter_book_price_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', help_text="L'auteur du livre", max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(default='', help_text="L'année de parution"),
        ),
    ]
