# Generated by Django 5.0.2 on 2024-02-21 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_alter_book_author_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default='', help_text='Le nombre de pages', validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
