# Generated by Django 5.0.2 on 2024-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(help_text="L'année de parution"),
        ),
    ]
