# Generated by Django 5.0.2 on 2024-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default='', help_text='Le nombre de pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', help_text='Le prix du livre', max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'year'), name='unique_book'),
        ),
    ]
