# Generated by Django 5.0.2 on 2024-02-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_alter_book_pages_alter_book_price_book_unique_book'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_book',
        ),
    ]
