# Generated by Django 5.0.2 on 2024-02-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
