# Generated by Django 5.0.2 on 2024-03-14 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(help_text='Le nombre de pages', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', help_text='Le prix du livre', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
